plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

evaluationDependsOn(":common")

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }

    include 'com.belerweb:pinyin4j:2.5.1'
    implementation 'com.belerweb:pinyin4j:2.5.1'

    // [新增] JEI Fabric 依赖
    compileOnly "mezz.jei:jei-1.21.8-fabric-api:24.2.0.6"
    // 开发环境运行时加载 JEI，方便测试
    modLocalRuntime "mezz.jei:jei-1.21.8-fabric:24.2.0.6"
}

processResources {
    filteringCharset = "UTF-8"

    def replaceProperties = [
            "version": rootProject.mod_version,
            "mod_id": rootProject.mod_id,
            "mod_name": rootProject.mod_name,
            "mod_name_json": rootProject.mod_name_json,
            "mod_description": rootProject.mod_description,
            "mod_description_json": rootProject.mod_description_json,
            "mod_license": rootProject.mod_license,
            "mod_authors": rootProject.mod_authors,
            "mod_homepage": rootProject.mod_homepage,
            "mod_sources": rootProject.mod_sources
    ]

    inputs.properties replaceProperties

    filesMatching("fabric.mod.json") {
        expand replaceProperties
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
