org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.20.1
enabled_platforms=fabric,forge

archives_base_name=recursivecraft
mod_version=0.62
maven_group=xczl

architectury_version=9.1.12

fabric_loader_version=0.17.3
fabric_api_version=0.92.6+1.20.1

forge_version=1.20.1-47.3.0

# === \u6838\u5FC3\u5143\u6570\u636E\u914D\u7F6E (\u65B0\u589E\u90E8\u5206) ===
mod_id=recursivecraft
mod_name=\u9012\u5F52\u5408\u6210
# \u6CE8\u610F\uFF1A\u63CF\u8FF0\u91CC\u7684\u6362\u884C\u5728properties\u91CC\u4E0D\u592A\u597D\u5904\u7406\uFF0C\u5EFA\u8BAE\u5199\u6210\u4E00\u884C
mod_description=\u57FA\u4E8E\u5F53\u524D\u80CC\u5305\u5185\u7684\u6750\u6599\uFF0C\u9009\u62E9\u6700\u4F18\u7684\u5408\u6210\u8DEF\u5F84\uFF0C\u5B9E\u73B0\u9012\u5F52\u5408\u6210\u3002
mod_license=GPL-2.0
mod_authors=xczl785
mod_homepage=https://gitee.com/XC750662297/RecursiveCraft
mod_sources=https://gitee.com/XC750662297/RecursiveCraft