org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

archives_base_name=recursivecraft
mod_version=0.84
maven_group=xczl

architectury_version=13.0.8

fabric_loader_version=0.17.3
fabric_api_version=0.116.12+1.21.1

neoforge_version=21.1.233

# === Core metadata ===
mod_id=recursivecraft
mod_name=RecursiveCraft
mod_name_json=RecursiveCraft
mod_description=Plan recursive crafting paths from your inventory and craft complex items automatically.
mod_description_json=Plan recursive crafting paths from your inventory and craft complex items automatically.
mod_license=MIT
mod_authors=xczl785
mod_homepage=https://github.com/xczl-785/RecursiveCraft
mod_sources=https://github.com/xczl-785/RecursiveCraft
